version: '3.8'

services:
  # Granite Chatbot Application
  granite-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: granite-chatbot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Replicate__ApiToken=${REPLICATE_API_TOKEN}

  # Caddy Reverse Proxy - Simple approach
  caddy:
    image: caddy:2-alpine
    container_name: granite-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from granite-chatbot.my.id --to localhost:8080
    depends_on:
      - granite-chatbot

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false